/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.sp.senac.views;

import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sKm
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipalExemplo2
     */
    public TelaPrincipal() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);

        // Setando Icone Janela
        
        URL IconRoute = getClass().getResource("/IconLogo-S.png");
        Image IconWindow = Toolkit.getDefaultToolkit().getImage(IconRoute);
        this.setIconImage(IconWindow);

        //Editar Header e Body Tabela Vendas
        tbVendas.getTableHeader().setFont(new Font("Sagoe UI", Font.BOLD, 13));
        tbVendas.getTableHeader().setOpaque(false);
        tbVendas.getTableHeader().setBackground(new Color(15, 76, 117));
        tbVendas.getTableHeader().setForeground(new Color(190, 190, 190));
        tbVendas.setRowHeight(25);
    }

    /**
     * Returns an ImageIcon, or null if the path was invalid.
     *
     * @param path
     * @param description
     * @return
     *
     * protected ImageIcon createImageIcon(String path, String description) {
     *
     * java.net.URL imgURL = getClass().getResource(path); if (imgURL != null) {
     * return new ImageIcon(imgURL, description); } else {
     * System.err.println("Couldn't find file: " + path); return null; } }
     *
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBg = new javax.swing.JPanel();
        panelContainer = new javax.swing.JPanel();
        btnGravar = new javax.swing.JButton();
        btnRemoverItem = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnFinalizar = new javax.swing.JButton();
        panelTable = new javax.swing.JPanel();
        sPaneListaVenda = new javax.swing.JScrollPane();
        tbVendas = new javax.swing.JTable();
        panelHeaderVendas = new javax.swing.JPanel();
        txtPesquisaProduto = new javax.swing.JTextField();
        panelFiltrosVendas = new javax.swing.JPanel();
        lblFiltroVendas = new javax.swing.JLabel();
        cbxTamanhoProdutoVendas = new javax.swing.JComboBox<>();
        cbxTipoProdutoVendas = new javax.swing.JComboBox<>();
        lblPesquisaProduto = new javax.swing.JLabel();
        btnPesquisaProduto = new javax.swing.JButton();
        lblCarrinho = new javax.swing.JLabel();
        panelTotal = new javax.swing.JPanel();
        lblTotal = new javax.swing.JLabel();
        lblRS = new javax.swing.JLabel();
        lblValorVendaAtual = new javax.swing.JLabel();
        panelSidebar = new javax.swing.JPanel();
        panelLogo = new javax.swing.JPanel();
        lblLojaRoupaLogo = new javax.swing.JLabel();
        lblLineProduto = new javax.swing.JLabel();
        panelLineFullLogoProduto = new javax.swing.JPanel();
        panelCadastroCliente = new javax.swing.JPanel();
        lblCadastroCliente = new javax.swing.JLabel();
        lblLogoCadastroCLiente = new javax.swing.JLabel();
        panelCadastroProduto = new javax.swing.JPanel();
        lblCadastroProduto = new javax.swing.JLabel();
        lblLogoCadastrarProduto = new javax.swing.JLabel();
        panelEstoqueVendas = new javax.swing.JPanel();
        lblEstoqueVendas = new javax.swing.JLabel();
        lblLogoEstoqueVendas = new javax.swing.JLabel();
        panelRelatorio = new javax.swing.JPanel();
        lblRelatorioCliente = new javax.swing.JLabel();
        lblLogoRelatorios = new javax.swing.JLabel();
        panelFooter = new javax.swing.JPanel();
        lblInformacoes = new javax.swing.JLabel();
        lblInformacoes2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Synthesia ®");

        panelBg.setBackground(new java.awt.Color(224, 224, 224));

        panelContainer.setBackground(new java.awt.Color(224, 224, 224));
        panelContainer.setForeground(new java.awt.Color(27, 38, 44));

        btnGravar.setBackground(new java.awt.Color(224, 224, 224));
        btnGravar.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        btnGravar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_buy_48px_1.png"))); // NOI18N
        btnGravar.setText("Gravar");
        btnGravar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        btnRemoverItem.setBackground(new java.awt.Color(224, 224, 224));
        btnRemoverItem.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        btnRemoverItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_trash_48px.png"))); // NOI18N
        btnRemoverItem.setText("Remover Item");
        btnRemoverItem.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnRemoverItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverItemActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(224, 224, 224));
        btnCancelar.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_cancel_48px.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnFinalizar.setBackground(new java.awt.Color(224, 224, 224));
        btnFinalizar.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        btnFinalizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_sell_stock_48px_2.png"))); // NOI18N
        btnFinalizar.setText("Finalizar");
        btnFinalizar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        panelTable.setBackground(new java.awt.Color(224, 224, 224));

        sPaneListaVenda.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N

        tbVendas.setBackground(new java.awt.Color(27, 38, 44));
        tbVendas.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        tbVendas.setForeground(new java.awt.Color(190, 190, 190));
        tbVendas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Horario", "ID", "Nome Produto", "Descrição", "Valor Unitário", "Subtotal"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbVendas.setToolTipText("");
        tbVendas.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tbVendas.setFocusable(false);
        tbVendas.setGridColor(new java.awt.Color(51, 51, 51));
        tbVendas.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tbVendas.setName("tbVendas"); // NOI18N
        tbVendas.setShowHorizontalLines(false);
        tbVendas.setShowVerticalLines(false);
        tbVendas.getTableHeader().setReorderingAllowed(false);
        tbVendas.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                tbVendasComponentResized(evt);
            }
        });
        tbVendas.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tbVendasPropertyChange(evt);
            }
        });
        sPaneListaVenda.setViewportView(tbVendas);
        if (tbVendas.getColumnModel().getColumnCount() > 0) {
            tbVendas.getColumnModel().getColumn(0).setResizable(false);
            tbVendas.getColumnModel().getColumn(0).setPreferredWidth(20);
            tbVendas.getColumnModel().getColumn(1).setResizable(false);
            tbVendas.getColumnModel().getColumn(1).setPreferredWidth(5);
            tbVendas.getColumnModel().getColumn(2).setResizable(false);
            tbVendas.getColumnModel().getColumn(2).setPreferredWidth(180);
            tbVendas.getColumnModel().getColumn(3).setResizable(false);
            tbVendas.getColumnModel().getColumn(3).setPreferredWidth(180);
            tbVendas.getColumnModel().getColumn(4).setResizable(false);
            tbVendas.getColumnModel().getColumn(4).setPreferredWidth(30);
            tbVendas.getColumnModel().getColumn(5).setResizable(false);
            tbVendas.getColumnModel().getColumn(5).setPreferredWidth(30);
        }

        panelHeaderVendas.setBackground(new java.awt.Color(224, 224, 224));
        panelHeaderVendas.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(15, 76, 117), 1, true));

        txtPesquisaProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesquisaProdutoActionPerformed(evt);
            }
        });

        panelFiltrosVendas.setBackground(new java.awt.Color(224, 224, 224));

        lblFiltroVendas.setBackground(new java.awt.Color(27, 38, 44));
        lblFiltroVendas.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        lblFiltroVendas.setForeground(new java.awt.Color(27, 38, 44));
        lblFiltroVendas.setText("Filtros:");

        cbxTamanhoProdutoVendas.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        cbxTamanhoProdutoVendas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione o tamanho", "Único", "PP", "P", "M", "G", "GG", "XGG", " " }));

        cbxTipoProdutoVendas.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        cbxTipoProdutoVendas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione um tipo de produto", "Bonés", "Camisetas", "Blusas", "Shorts", "Calças" }));

        javax.swing.GroupLayout panelFiltrosVendasLayout = new javax.swing.GroupLayout(panelFiltrosVendas);
        panelFiltrosVendas.setLayout(panelFiltrosVendasLayout);
        panelFiltrosVendasLayout.setHorizontalGroup(
            panelFiltrosVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFiltrosVendasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFiltrosVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFiltroVendas)
                    .addGroup(panelFiltrosVendasLayout.createSequentialGroup()
                        .addComponent(cbxTamanhoProdutoVendas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbxTipoProdutoVendas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        panelFiltrosVendasLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cbxTamanhoProdutoVendas, cbxTipoProdutoVendas});

        panelFiltrosVendasLayout.setVerticalGroup(
            panelFiltrosVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFiltrosVendasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFiltroVendas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFiltrosVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxTamanhoProdutoVendas, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxTipoProdutoVendas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11))
        );

        panelFiltrosVendasLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cbxTamanhoProdutoVendas, cbxTipoProdutoVendas});

        lblPesquisaProduto.setBackground(new java.awt.Color(27, 38, 44));
        lblPesquisaProduto.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        lblPesquisaProduto.setForeground(new java.awt.Color(27, 38, 44));
        lblPesquisaProduto.setText("Buscar produto: ");

        btnPesquisaProduto.setBackground(new java.awt.Color(224, 224, 224));
        btnPesquisaProduto.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        btnPesquisaProduto.setForeground(new java.awt.Color(27, 38, 44));
        btnPesquisaProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_plus_math_24px.png"))); // NOI18N

        javax.swing.GroupLayout panelHeaderVendasLayout = new javax.swing.GroupLayout(panelHeaderVendas);
        panelHeaderVendas.setLayout(panelHeaderVendasLayout);
        panelHeaderVendasLayout.setHorizontalGroup(
            panelHeaderVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHeaderVendasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelHeaderVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPesquisaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelHeaderVendasLayout.createSequentialGroup()
                        .addComponent(txtPesquisaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnPesquisaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelFiltrosVendas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelHeaderVendasLayout.setVerticalGroup(
            panelHeaderVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHeaderVendasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelHeaderVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelHeaderVendasLayout.createSequentialGroup()
                        .addComponent(lblPesquisaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addGroup(panelHeaderVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnPesquisaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(txtPesquisaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(panelFiltrosVendas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        lblCarrinho.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        lblCarrinho.setForeground(new java.awt.Color(27, 38, 44));
        lblCarrinho.setText("Carrinho:");

        javax.swing.GroupLayout panelTableLayout = new javax.swing.GroupLayout(panelTable);
        panelTable.setLayout(panelTableLayout);
        panelTableLayout.setHorizontalGroup(
            panelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTableLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sPaneListaVenda)
                    .addComponent(panelHeaderVendas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelTableLayout.createSequentialGroup()
                        .addComponent(lblCarrinho)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        panelTableLayout.setVerticalGroup(
            panelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTableLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(panelHeaderVendas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(lblCarrinho)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sPaneListaVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelTotal.setBackground(new java.awt.Color(27, 38, 44));

        lblTotal.setFont(new java.awt.Font("Courier New", 1, 48)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(190, 190, 190));
        lblTotal.setText("Total");

        lblRS.setFont(new java.awt.Font("Courier New", 1, 48)); // NOI18N
        lblRS.setForeground(new java.awt.Color(190, 190, 190));
        lblRS.setText("R$");

        lblValorVendaAtual.setFont(new java.awt.Font("Courier New", 1, 48)); // NOI18N
        lblValorVendaAtual.setForeground(new java.awt.Color(190, 190, 190));
        lblValorVendaAtual.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblValorVendaAtual.setText("350,00");
        lblValorVendaAtual.setFocusable(false);
        lblValorVendaAtual.setVerifyInputWhenFocusTarget(false);

        javax.swing.GroupLayout panelTotalLayout = new javax.swing.GroupLayout(panelTotal);
        panelTotal.setLayout(panelTotalLayout);
        panelTotalLayout.setHorizontalGroup(
            panelTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTotalLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblRS)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 390, Short.MAX_VALUE)
                .addComponent(lblValorVendaAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelTotalLayout.setVerticalGroup(
            panelTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTotalLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(panelTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRS, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblValorVendaAtual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout panelContainerLayout = new javax.swing.GroupLayout(panelContainer);
        panelContainer.setLayout(panelContainerLayout);
        panelContainerLayout.setHorizontalGroup(
            panelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContainerLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(panelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelContainerLayout.createSequentialGroup()
                        .addComponent(btnRemoverItem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGravar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnFinalizar))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelContainerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panelContainerLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCancelar, btnFinalizar, btnGravar});

        panelContainerLayout.setVerticalGroup(
            panelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelContainerLayout.createSequentialGroup()
                        .addGroup(panelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnRemoverItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE))
                        .addGap(1, 1, 1))
                    .addGroup(panelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnGravar, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnFinalizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        panelContainerLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnCancelar, btnFinalizar, btnRemoverItem});

        panelSidebar.setBackground(new java.awt.Color(15, 76, 117));

        panelLogo.setBackground(new java.awt.Color(15, 76, 117));
        panelLogo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(190, 176, 40), 1, true));
        panelLogo.setForeground(new java.awt.Color(190, 176, 40));
        panelLogo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLojaRoupaLogo.setFont(new java.awt.Font("Old English Text MT", 1, 48)); // NOI18N
        lblLojaRoupaLogo.setForeground(new java.awt.Color(190, 176, 40));
        lblLojaRoupaLogo.setText("Synthesia");
        panelLogo.add(lblLojaRoupaLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 230, 41));

        lblLineProduto.setBackground(new java.awt.Color(190, 190, 190));
        lblLineProduto.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblLineProduto.setForeground(new java.awt.Color(190, 176, 40));
        lblLineProduto.setText("____________________________________");
        panelLogo.add(lblLineProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 300, -1));

        panelLineFullLogoProduto.setBackground(new java.awt.Color(190, 176, 40));

        javax.swing.GroupLayout panelLineFullLogoProdutoLayout = new javax.swing.GroupLayout(panelLineFullLogoProduto);
        panelLineFullLogoProduto.setLayout(panelLineFullLogoProdutoLayout);
        panelLineFullLogoProdutoLayout.setHorizontalGroup(
            panelLineFullLogoProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 290, Short.MAX_VALUE)
        );
        panelLineFullLogoProdutoLayout.setVerticalGroup(
            panelLineFullLogoProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        panelLogo.add(panelLineFullLogoProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 290, 10));

        panelCadastroCliente.setBackground(new java.awt.Color(50, 130, 184));
        panelCadastroCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panelCadastroCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelCadastroClienteMouseClicked(evt);
            }
        });

        lblCadastroCliente.setBackground(new java.awt.Color(204, 204, 204));
        lblCadastroCliente.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        lblCadastroCliente.setForeground(new java.awt.Color(190, 190, 190));
        lblCadastroCliente.setText("Cadastro de Cliente");

        lblLogoCadastroCLiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_add_user_group_man_man_32px_2.png"))); // NOI18N

        javax.swing.GroupLayout panelCadastroClienteLayout = new javax.swing.GroupLayout(panelCadastroCliente);
        panelCadastroCliente.setLayout(panelCadastroClienteLayout);
        panelCadastroClienteLayout.setHorizontalGroup(
            panelCadastroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCadastroClienteLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblLogoCadastroCLiente)
                .addGap(30, 30, 30)
                .addComponent(lblCadastroCliente)
                .addGap(16, 16, 16))
        );
        panelCadastroClienteLayout.setVerticalGroup(
            panelCadastroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCadastroClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCadastroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLogoCadastroCLiente, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(lblCadastroCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        panelCadastroProduto.setBackground(new java.awt.Color(50, 130, 184));
        panelCadastroProduto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panelCadastroProduto.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        panelCadastroProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelCadastroProdutoMouseClicked(evt);
            }
        });

        lblCadastroProduto.setBackground(new java.awt.Color(204, 204, 204));
        lblCadastroProduto.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        lblCadastroProduto.setForeground(new java.awt.Color(190, 190, 190));
        lblCadastroProduto.setText("Cadastro de Produto");

        lblLogoCadastrarProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_add_shopping_cart_32px_3.png"))); // NOI18N

        javax.swing.GroupLayout panelCadastroProdutoLayout = new javax.swing.GroupLayout(panelCadastroProduto);
        panelCadastroProduto.setLayout(panelCadastroProdutoLayout);
        panelCadastroProdutoLayout.setHorizontalGroup(
            panelCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCadastroProdutoLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblLogoCadastrarProduto)
                .addGap(30, 30, 30)
                .addComponent(lblCadastroProduto)
                .addGap(17, 17, 17))
        );
        panelCadastroProdutoLayout.setVerticalGroup(
            panelCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCadastroProdutoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLogoCadastrarProduto, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(lblCadastroProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        panelEstoqueVendas.setBackground(new java.awt.Color(50, 130, 184));
        panelEstoqueVendas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panelEstoqueVendas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelEstoqueVendasMouseClicked(evt);
            }
        });

        lblEstoqueVendas.setBackground(new java.awt.Color(204, 204, 204));
        lblEstoqueVendas.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        lblEstoqueVendas.setForeground(new java.awt.Color(190, 190, 190));
        lblEstoqueVendas.setText("Estoque");

        lblLogoEstoqueVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_new_product_32px.png"))); // NOI18N

        javax.swing.GroupLayout panelEstoqueVendasLayout = new javax.swing.GroupLayout(panelEstoqueVendas);
        panelEstoqueVendas.setLayout(panelEstoqueVendasLayout);
        panelEstoqueVendasLayout.setHorizontalGroup(
            panelEstoqueVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEstoqueVendasLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblLogoEstoqueVendas)
                .addGap(30, 30, 30)
                .addComponent(lblEstoqueVendas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelEstoqueVendasLayout.setVerticalGroup(
            panelEstoqueVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEstoqueVendasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEstoqueVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEstoqueVendasLayout.createSequentialGroup()
                        .addComponent(lblLogoEstoqueVendas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(14, 14, 14))
                    .addGroup(panelEstoqueVendasLayout.createSequentialGroup()
                        .addComponent(lblEstoqueVendas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        panelRelatorio.setBackground(new java.awt.Color(50, 130, 184));
        panelRelatorio.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panelRelatorio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelRelatorioMouseClicked(evt);
            }
        });

        lblRelatorioCliente.setBackground(new java.awt.Color(204, 204, 204));
        lblRelatorioCliente.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        lblRelatorioCliente.setForeground(new java.awt.Color(190, 190, 190));
        lblRelatorioCliente.setText("Relatórios");

        lblLogoRelatorios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_combo_chart_32px_2.png"))); // NOI18N

        javax.swing.GroupLayout panelRelatorioLayout = new javax.swing.GroupLayout(panelRelatorio);
        panelRelatorio.setLayout(panelRelatorioLayout);
        panelRelatorioLayout.setHorizontalGroup(
            panelRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRelatorioLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblLogoRelatorios)
                .addGap(30, 30, 30)
                .addComponent(lblRelatorioCliente)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelRelatorioLayout.setVerticalGroup(
            panelRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRelatorioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLogoRelatorios, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(lblRelatorioCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        panelFooter.setBackground(new java.awt.Color(15, 76, 117));

        lblInformacoes.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        lblInformacoes.setForeground(new java.awt.Color(190, 190, 190));
        lblInformacoes.setText("Mais informações  -");

        lblInformacoes2.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        lblInformacoes2.setForeground(new java.awt.Color(190, 190, 190));
        lblInformacoes2.setText("www.sp.senac.br");

        javax.swing.GroupLayout panelFooterLayout = new javax.swing.GroupLayout(panelFooter);
        panelFooter.setLayout(panelFooterLayout);
        panelFooterLayout.setHorizontalGroup(
            panelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFooterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblInformacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInformacoes2)
                .addContainerGap())
        );
        panelFooterLayout.setVerticalGroup(
            panelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFooterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInformacoes)
                    .addComponent(lblInformacoes2))
                .addContainerGap())
        );

        javax.swing.GroupLayout panelSidebarLayout = new javax.swing.GroupLayout(panelSidebar);
        panelSidebar.setLayout(panelSidebarLayout);
        panelSidebarLayout.setHorizontalGroup(
            panelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCadastroCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelCadastroProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelRelatorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelEstoqueVendas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelSidebarLayout.createSequentialGroup()
                .addGroup(panelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSidebarLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(panelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelSidebarLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(panelFooter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelSidebarLayout.setVerticalGroup(
            panelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSidebarLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(panelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(panelCadastroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelCadastroProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelEstoqueVendas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 319, Short.MAX_VALUE)
                .addComponent(panelFooter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelBgLayout = new javax.swing.GroupLayout(panelBg);
        panelBg.setLayout(panelBgLayout);
        panelBgLayout.setHorizontalGroup(
            panelBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBgLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(panelSidebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelBgLayout.setVerticalGroup(
            panelBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelSidebar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelContainer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbVendasPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tbVendasPropertyChange

    }//GEN-LAST:event_tbVendasPropertyChange

    private void tbVendasComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_tbVendasComponentResized

    }//GEN-LAST:event_tbVendasComponentResized

    private void txtPesquisaProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisaProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesquisaProdutoActionPerformed

    private void panelRelatorioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRelatorioMouseClicked
        TelaRelatorio newTela = new TelaRelatorio();
        newTela.setVisible(true);
    }//GEN-LAST:event_panelRelatorioMouseClicked

    private void panelCadastroProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelCadastroProdutoMouseClicked
        TelaProduto newTela = new TelaProduto();
        newTela.setVisible(true);
    }//GEN-LAST:event_panelCadastroProdutoMouseClicked

    private void panelCadastroClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelCadastroClienteMouseClicked
        TelaCliente newTela = new TelaCliente();
        newTela.setVisible(true);
    }//GEN-LAST:event_panelCadastroClienteMouseClicked

    private void panelEstoqueVendasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelEstoqueVendasMouseClicked

        TelaEstoque newTela = new TelaEstoque();
        newTela.setVisible(true);
    }//GEN-LAST:event_panelEstoqueVendasMouseClicked

    private void btnRemoverItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverItemActionPerformed
        DefaultTableModel dtmCarrinho = (DefaultTableModel) tbVendas.getModel();

        boolean resultadoRemove = false;

        try {
            if (tbVendas.getSelectedRow() >= 0) {
                dtmCarrinho.removeRow(tbVendas.getSelectedRow());
                tbVendas.setModel(dtmCarrinho);
                resultadoRemove = true;
            } else {
                JOptionPane.showMessageDialog(null, "Favor selecionar uma linha");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao remover o produto, tente novamente!", "Erro", JOptionPane.ERROR);
        } finally {
            if (resultadoRemove == true) {
                JOptionPane.showMessageDialog(this, "Produto removido com sucesso!", "Aviso", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnRemoverItemActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnFinalizar;
    private javax.swing.JButton btnGravar;
    private javax.swing.JButton btnPesquisaProduto;
    private javax.swing.JButton btnRemoverItem;
    private javax.swing.JComboBox<String> cbxTamanhoProdutoVendas;
    private javax.swing.JComboBox<String> cbxTipoProdutoVendas;
    private javax.swing.JLabel lblCadastroCliente;
    private javax.swing.JLabel lblCadastroProduto;
    private javax.swing.JLabel lblCarrinho;
    private javax.swing.JLabel lblEstoqueVendas;
    private javax.swing.JLabel lblFiltroVendas;
    private javax.swing.JLabel lblInformacoes;
    private javax.swing.JLabel lblInformacoes2;
    private javax.swing.JLabel lblLineProduto;
    private javax.swing.JLabel lblLogoCadastrarProduto;
    private javax.swing.JLabel lblLogoCadastroCLiente;
    private javax.swing.JLabel lblLogoEstoqueVendas;
    private javax.swing.JLabel lblLogoRelatorios;
    private javax.swing.JLabel lblLojaRoupaLogo;
    private javax.swing.JLabel lblPesquisaProduto;
    private javax.swing.JLabel lblRS;
    private javax.swing.JLabel lblRelatorioCliente;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblValorVendaAtual;
    private javax.swing.JPanel panelBg;
    private javax.swing.JPanel panelCadastroCliente;
    private javax.swing.JPanel panelCadastroProduto;
    private javax.swing.JPanel panelContainer;
    private javax.swing.JPanel panelEstoqueVendas;
    private javax.swing.JPanel panelFiltrosVendas;
    private javax.swing.JPanel panelFooter;
    private javax.swing.JPanel panelHeaderVendas;
    private javax.swing.JPanel panelLineFullLogoProduto;
    private javax.swing.JPanel panelLogo;
    private javax.swing.JPanel panelRelatorio;
    private javax.swing.JPanel panelSidebar;
    private javax.swing.JPanel panelTable;
    private javax.swing.JPanel panelTotal;
    private javax.swing.JScrollPane sPaneListaVenda;
    private javax.swing.JTable tbVendas;
    private javax.swing.JTextField txtPesquisaProduto;
    // End of variables declaration//GEN-END:variables
}
