/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.sp.senac.views;

import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sKm
 */
public class TelaCliente extends javax.swing.JFrame {

    /**
     * Creates new form CadastroCliente
     */
    public TelaCliente() {
        initComponents();
        this.setLocationRelativeTo(null);

        // Setando Icone Janela
        URL IconRoute = getClass().getResource("/IconLogo-S.png");
        Image IconWindow = Toolkit.getDefaultToolkit().getImage(IconRoute);
        this.setIconImage(IconWindow);

        // Editar Header e Body Tabela Clientes
        tbClientes.getTableHeader().setFont(new Font("Sagoe UI", Font.BOLD, 13));
        tbClientes.getTableHeader().setOpaque(false);
        tbClientes.getTableHeader().setBackground(new Color(15, 76, 117));
        tbClientes.getTableHeader().setForeground(new Color(190, 190, 190));
        tbClientes.setRowHeight(25);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        panelBg = new javax.swing.JPanel();
        panelSidebarTop = new javax.swing.JPanel();
        panelLogoProduto = new javax.swing.JPanel();
        lblLojaRoupaLogoProduto = new javax.swing.JLabel();
        lblLineProduto = new javax.swing.JLabel();
        panelLineFullLogoProduto = new javax.swing.JPanel();
        lblCadastroCliente = new javax.swing.JLabel();
        panelContainer = new javax.swing.JPanel();
        lblID = new javax.swing.JLabel();
        txtIdCliente = new javax.swing.JTextField();
        lblNomeCliente = new javax.swing.JLabel();
        txtNomeCliente = new javax.swing.JTextField();
        lblEnderecoCliente = new javax.swing.JLabel();
        txtEnderecoCliente = new javax.swing.JTextField();
        lblCpfCliente = new javax.swing.JLabel();
        formatCpfCliente = new javax.swing.JFormattedTextField();
        lblEmailCliente = new javax.swing.JLabel();
        txtEmailCliente = new javax.swing.JTextField();
        lblSexoCliente = new javax.swing.JLabel();
        cbxSexoCliente = new javax.swing.JComboBox<>();
        lblTelefoneCliente = new javax.swing.JLabel();
        formatTelefoneCliente = new javax.swing.JFormattedTextField();
        lblCelularCliente = new javax.swing.JLabel();
        formatCelularCliente = new javax.swing.JFormattedTextField();
        separadorBotoesUp = new javax.swing.JSeparator();
        panelBotoesCliente = new javax.swing.JPanel();
        btnCancelarCadastro = new javax.swing.JButton();
        btnRemoverCliente = new javax.swing.JButton();
        btnCadastrar = new javax.swing.JButton();
        btnEditarCliente = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnLimparCadastro = new javax.swing.JButton();
        separadorBotoesDown = new javax.swing.JSeparator();
        panelTabelaCliente = new javax.swing.JPanel();
        spanelClientes = new javax.swing.JScrollPane();
        tbClientes = new javax.swing.JTable();

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastrar Cliente");
        setResizable(false);

        panelBg.setBackground(new java.awt.Color(224, 224, 224));

        panelSidebarTop.setBackground(new java.awt.Color(15, 76, 117));

        panelLogoProduto.setBackground(new java.awt.Color(15, 76, 117));
        panelLogoProduto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(190, 176, 40), 1, true));
        panelLogoProduto.setForeground(new java.awt.Color(190, 176, 40));
        panelLogoProduto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLojaRoupaLogoProduto.setFont(new java.awt.Font("Old English Text MT", 1, 48)); // NOI18N
        lblLojaRoupaLogoProduto.setForeground(new java.awt.Color(190, 176, 40));
        lblLojaRoupaLogoProduto.setText("Synthesia");
        panelLogoProduto.add(lblLojaRoupaLogoProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 240, 41));

        lblLineProduto.setBackground(new java.awt.Color(190, 190, 190));
        lblLineProduto.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblLineProduto.setForeground(new java.awt.Color(190, 176, 40));
        lblLineProduto.setText("____________________________________");
        panelLogoProduto.add(lblLineProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 300, -1));

        panelLineFullLogoProduto.setBackground(new java.awt.Color(190, 176, 40));

        javax.swing.GroupLayout panelLineFullLogoProdutoLayout = new javax.swing.GroupLayout(panelLineFullLogoProduto);
        panelLineFullLogoProduto.setLayout(panelLineFullLogoProdutoLayout);
        panelLineFullLogoProdutoLayout.setHorizontalGroup(
            panelLineFullLogoProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 290, Short.MAX_VALUE)
        );
        panelLineFullLogoProdutoLayout.setVerticalGroup(
            panelLineFullLogoProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        panelLogoProduto.add(panelLineFullLogoProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 290, 10));

        lblCadastroCliente.setFont(new java.awt.Font("Courier New", 1, 36)); // NOI18N
        lblCadastroCliente.setForeground(new java.awt.Color(255, 255, 255));
        lblCadastroCliente.setText("Cadastro de Cliente");

        javax.swing.GroupLayout panelSidebarTopLayout = new javax.swing.GroupLayout(panelSidebarTop);
        panelSidebarTop.setLayout(panelSidebarTopLayout);
        panelSidebarTopLayout.setHorizontalGroup(
            panelSidebarTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSidebarTopLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(panelLogoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCadastroCliente)
                .addGap(50, 50, 50))
        );
        panelSidebarTopLayout.setVerticalGroup(
            panelSidebarTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSidebarTopLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(panelSidebarTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelLogoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCadastroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        panelContainer.setBackground(new java.awt.Color(224, 224, 224));
        panelContainer.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(15, 76, 117), 1, true));
        panelContainer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblID.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        lblID.setForeground(new java.awt.Color(27, 38, 44));
        lblID.setText("ID:");
        panelContainer.add(lblID, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 19, -1, -1));

        txtIdCliente.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        txtIdCliente.setForeground(new java.awt.Color(27, 38, 44));
        panelContainer.add(txtIdCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 40, 254, 30));

        lblNomeCliente.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        lblNomeCliente.setForeground(new java.awt.Color(27, 38, 44));
        lblNomeCliente.setText("Nome:*");
        panelContainer.add(lblNomeCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 19, -1, -1));

        txtNomeCliente.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        txtNomeCliente.setForeground(new java.awt.Color(27, 38, 44));
        panelContainer.add(txtNomeCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 40, 335, 30));

        lblEnderecoCliente.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        lblEnderecoCliente.setForeground(new java.awt.Color(27, 38, 44));
        lblEnderecoCliente.setText("Endereço:*");
        panelContainer.add(lblEnderecoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 20, -1, -1));

        txtEnderecoCliente.setForeground(new java.awt.Color(27, 38, 44));
        panelContainer.add(txtEnderecoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 40, 550, 30));

        lblCpfCliente.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        lblCpfCliente.setForeground(new java.awt.Color(27, 38, 44));
        lblCpfCliente.setText("CPF:*");
        panelContainer.add(lblCpfCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        formatCpfCliente.setForeground(new java.awt.Color(27, 38, 44));
        try {
            formatCpfCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        panelContainer.add(formatCpfCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 240, 30));

        lblEmailCliente.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        lblEmailCliente.setForeground(new java.awt.Color(27, 38, 44));
        lblEmailCliente.setText("Email:*");
        panelContainer.add(lblEmailCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, -1, -1));

        txtEmailCliente.setForeground(new java.awt.Color(27, 38, 44));
        panelContainer.add(txtEmailCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, 330, 30));

        lblSexoCliente.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        lblSexoCliente.setForeground(new java.awt.Color(27, 38, 44));
        lblSexoCliente.setText("Sexo:*");
        panelContainer.add(lblSexoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 110, -1, -1));

        cbxSexoCliente.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        cbxSexoCliente.setForeground(new java.awt.Color(27, 38, 44));
        cbxSexoCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione um gênero", "Masculino", "Feminino", "Outros", " " }));
        panelContainer.add(cbxSexoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 130, 190, 30));

        lblTelefoneCliente.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        lblTelefoneCliente.setForeground(new java.awt.Color(27, 38, 44));
        lblTelefoneCliente.setText("Telefone:");
        panelContainer.add(lblTelefoneCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 110, -1, -1));

        formatTelefoneCliente.setForeground(new java.awt.Color(27, 38, 44));
        try {
            formatTelefoneCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        formatTelefoneCliente.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        panelContainer.add(formatTelefoneCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 130, 130, 30));

        lblCelularCliente.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        lblCelularCliente.setForeground(new java.awt.Color(27, 38, 44));
        lblCelularCliente.setText("Celular:*");
        panelContainer.add(lblCelularCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 110, -1, -1));

        formatCelularCliente.setForeground(new java.awt.Color(27, 38, 44));
        try {
            formatCelularCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #-####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        formatCelularCliente.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        panelContainer.add(formatCelularCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 130, 170, 30));

        panelBotoesCliente.setBackground(new java.awt.Color(224, 224, 224));

        btnCancelarCadastro.setBackground(new java.awt.Color(224, 224, 224));
        btnCancelarCadastro.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        btnCancelarCadastro.setForeground(new java.awt.Color(27, 38, 44));
        btnCancelarCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_cancel_24px.png"))); // NOI18N
        btnCancelarCadastro.setText("Cancelar");
        btnCancelarCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarCadastroActionPerformed(evt);
            }
        });

        btnRemoverCliente.setBackground(new java.awt.Color(224, 224, 224));
        btnRemoverCliente.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        btnRemoverCliente.setForeground(new java.awt.Color(27, 38, 44));
        btnRemoverCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_trash_24px.png"))); // NOI18N
        btnRemoverCliente.setText("Remover");
        btnRemoverCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverClienteActionPerformed(evt);
            }
        });

        btnCadastrar.setBackground(new java.awt.Color(224, 224, 224));
        btnCadastrar.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        btnCadastrar.setForeground(new java.awt.Color(27, 38, 44));
        btnCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_registration_24px.png"))); // NOI18N
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        btnEditarCliente.setBackground(new java.awt.Color(224, 224, 224));
        btnEditarCliente.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        btnEditarCliente.setForeground(new java.awt.Color(27, 38, 44));
        btnEditarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_edit_24px.png"))); // NOI18N
        btnEditarCliente.setText("Editar");

        btnSalvar.setBackground(new java.awt.Color(224, 224, 224));
        btnSalvar.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        btnSalvar.setForeground(new java.awt.Color(27, 38, 44));
        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_save_24px.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnLimparCadastro.setBackground(new java.awt.Color(224, 224, 224));
        btnLimparCadastro.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        btnLimparCadastro.setForeground(new java.awt.Color(27, 38, 44));
        btnLimparCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_broom_24px.png"))); // NOI18N
        btnLimparCadastro.setText("Limpar");
        btnLimparCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparCadastroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBotoesClienteLayout = new javax.swing.GroupLayout(panelBotoesCliente);
        panelBotoesCliente.setLayout(panelBotoesClienteLayout);
        panelBotoesClienteLayout.setHorizontalGroup(
            panelBotoesClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotoesClienteLayout.createSequentialGroup()
                .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(btnSalvar)
                .addGap(259, 259, 259)
                .addComponent(btnLimparCadastro)
                .addGap(40, 40, 40)
                .addComponent(btnEditarCliente)
                .addGap(40, 40, 40)
                .addComponent(btnRemoverCliente)
                .addGap(40, 40, 40)
                .addComponent(btnCancelarCadastro))
        );

        panelBotoesClienteLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCadastrar, btnCancelarCadastro, btnEditarCliente, btnLimparCadastro, btnRemoverCliente, btnSalvar});

        panelBotoesClienteLayout.setVerticalGroup(
            panelBotoesClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotoesClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBotoesClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBotoesClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnEditarCliente)
                        .addComponent(btnRemoverCliente)
                        .addComponent(btnCancelarCadastro)
                        .addComponent(btnLimparCadastro))
                    .addGroup(panelBotoesClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSalvar)))
                .addContainerGap())
        );

        panelBotoesClienteLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnCadastrar, btnCancelarCadastro, btnEditarCliente, btnLimparCadastro, btnRemoverCliente, btnSalvar});

        panelTabelaCliente.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(15, 76, 117), 1, true));

        tbClientes.setBackground(new java.awt.Color(27, 38, 44));
        tbClientes.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        tbClientes.setForeground(new java.awt.Color(190, 190, 190));
        tbClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "CPF", "Endereço", "Email", "Celular"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbClientes.setToolTipText("Tabela Clientes");
        tbClientes.setFocusable(false);
        tbClientes.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tbClientes.setShowHorizontalLines(false);
        tbClientes.setShowVerticalLines(false);
        tbClientes.getTableHeader().setReorderingAllowed(false);
        spanelClientes.setViewportView(tbClientes);
        if (tbClientes.getColumnModel().getColumnCount() > 0) {
            tbClientes.getColumnModel().getColumn(0).setResizable(false);
            tbClientes.getColumnModel().getColumn(0).setPreferredWidth(5);
            tbClientes.getColumnModel().getColumn(1).setResizable(false);
            tbClientes.getColumnModel().getColumn(1).setPreferredWidth(25);
            tbClientes.getColumnModel().getColumn(2).setResizable(false);
            tbClientes.getColumnModel().getColumn(2).setPreferredWidth(15);
            tbClientes.getColumnModel().getColumn(3).setResizable(false);
            tbClientes.getColumnModel().getColumn(3).setPreferredWidth(25);
            tbClientes.getColumnModel().getColumn(4).setResizable(false);
            tbClientes.getColumnModel().getColumn(5).setResizable(false);
            tbClientes.getColumnModel().getColumn(5).setPreferredWidth(15);
        }

        javax.swing.GroupLayout panelTabelaClienteLayout = new javax.swing.GroupLayout(panelTabelaCliente);
        panelTabelaCliente.setLayout(panelTabelaClienteLayout);
        panelTabelaClienteLayout.setHorizontalGroup(
            panelTabelaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTabelaClienteLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(spanelClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 1302, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelTabelaClienteLayout.setVerticalGroup(
            panelTabelaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTabelaClienteLayout.createSequentialGroup()
                .addComponent(spanelClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelBgLayout = new javax.swing.GroupLayout(panelBg);
        panelBg.setLayout(panelBgLayout);
        panelBgLayout.setHorizontalGroup(
            panelBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelSidebarTop, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelBgLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(panelBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(separadorBotoesDown)
                    .addComponent(panelTabelaCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelContainer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(separadorBotoesUp)
                    .addComponent(panelBotoesCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(50, 50, 50))
        );
        panelBgLayout.setVerticalGroup(
            panelBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBgLayout.createSequentialGroup()
                .addComponent(panelSidebarTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(panelContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(separadorBotoesUp, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelBotoesCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separadorBotoesDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(panelTabelaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        String idCliente = txtIdCliente.getText();
        String nomeCliente = txtNomeCliente.getText();
        String enderecoCliente = txtEnderecoCliente.getText();
        String cpfCliente = formatCpfCliente.getText();
        String emailCliente = txtEmailCliente.getText();
        String celCliente = formatCelularCliente.getText();

        // Validação de campos simples
        try {
            if ((cbxSexoCliente.getSelectedIndex() != 0)
                    && (txtNomeCliente.getText().length() > 5)
                    && (txtEnderecoCliente.getText().length() > 10)
                    && (formatCpfCliente.getText().length() > 0)
                    && (txtEmailCliente.getText().length() > 0)
                    && (formatCelularCliente.getText().length() > 0)) {
                
                JOptionPane.showMessageDialog(this, "Cadastro realizado com sucesso! ", "Aviso", JOptionPane.WARNING_MESSAGE);
                
                DefaultTableModel dtmClientes = (DefaultTableModel) tbClientes.getModel();
                dtmClientes.addRow(new Object[]{
                    idCliente,
                    nomeCliente,
                    cpfCliente,
                    enderecoCliente,
                    emailCliente,
                    celCliente,});

            } else {
                JOptionPane.showMessageDialog(this, "Alguns campos não foram preenchidos corretamente! ", "Aviso", JOptionPane.WARNING_MESSAGE);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao cadastrar o cliente!", "Erro", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnCancelarCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarCadastroActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelarCadastroActionPerformed

    private void btnRemoverClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverClienteActionPerformed
        DefaultTableModel dtmClientes = (DefaultTableModel) tbClientes.getModel();

        boolean resultadoRemove = false;

        try {
            if (tbClientes.getSelectedRow() >= 0) {
                dtmClientes.removeRow(tbClientes.getSelectedRow());
                tbClientes.setModel(dtmClientes);
                resultadoRemove = true;
            } else {
                JOptionPane.showMessageDialog(null, "Favor selecionar uma linha");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao remover o cliente, tente novamente!", "Erro", JOptionPane.ERROR);
        } finally {
            if (resultadoRemove == true) {
                JOptionPane.showMessageDialog(this, "Cliente removido com sucesso!", "Aviso", JOptionPane.INFORMATION_MESSAGE);
            }
        }


    }//GEN-LAST:event_btnRemoverClienteActionPerformed

    private void btnLimparCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparCadastroActionPerformed
        limparCadastro();
    }//GEN-LAST:event_btnLimparCadastroActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        validate();
    }//GEN-LAST:event_btnSalvarActionPerformed

    //Metodo para Limpar Cadastro Cliente
    private void limparCadastro() {
        txtIdCliente.setText("");
        txtNomeCliente.setText("");
        txtEnderecoCliente.setText("");
        formatCpfCliente.setText("");
        txtEmailCliente.setText("");
        cbxSexoCliente.setSelectedIndex(0);
        formatTelefoneCliente.setText("");
        formatCelularCliente.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnCancelarCadastro;
    private javax.swing.JButton btnEditarCliente;
    private javax.swing.JButton btnLimparCadastro;
    private javax.swing.JButton btnRemoverCliente;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cbxSexoCliente;
    private javax.swing.JFormattedTextField formatCelularCliente;
    private javax.swing.JFormattedTextField formatCpfCliente;
    private javax.swing.JFormattedTextField formatTelefoneCliente;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JLabel lblCadastroCliente;
    private javax.swing.JLabel lblCelularCliente;
    private javax.swing.JLabel lblCpfCliente;
    private javax.swing.JLabel lblEmailCliente;
    private javax.swing.JLabel lblEnderecoCliente;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblLineProduto;
    private javax.swing.JLabel lblLojaRoupaLogoProduto;
    private javax.swing.JLabel lblNomeCliente;
    private javax.swing.JLabel lblSexoCliente;
    private javax.swing.JLabel lblTelefoneCliente;
    private javax.swing.JPanel panelBg;
    private javax.swing.JPanel panelBotoesCliente;
    private javax.swing.JPanel panelContainer;
    private javax.swing.JPanel panelLineFullLogoProduto;
    private javax.swing.JPanel panelLogoProduto;
    private javax.swing.JPanel panelSidebarTop;
    private javax.swing.JPanel panelTabelaCliente;
    private javax.swing.JSeparator separadorBotoesDown;
    private javax.swing.JSeparator separadorBotoesUp;
    private javax.swing.JScrollPane spanelClientes;
    private javax.swing.JTable tbClientes;
    private javax.swing.JTextField txtEmailCliente;
    private javax.swing.JTextField txtEnderecoCliente;
    private javax.swing.JTextField txtIdCliente;
    private javax.swing.JTextField txtNomeCliente;
    // End of variables declaration//GEN-END:variables
}
